Vagrant.configure(2) do |config|
  
   config.vm.box = "boxcutter/ubuntu1404-desktop" 
   config.vm.box_check_update = false
   config.vm.provider "virtualbox" do |vb| 
     vb.gui = true  
     vb.memory = "2048"
   end
 
   config.vm.provision "shell", inline: <<-SHELL
   sudo add-apt-repository -y ppa:webupd8team/java
   sudo apt-get update
   echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
   sudo apt-get install -y oracle-java8-installer
   sudo reboot
   SHELL
end
